kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: localhost:5000/z1y/hello:13.10
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
        - name: hello2
          image: localhost:5000/z1y/hwa:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 81
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
    name: hello
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
    selector:
      app: hello

---

kind: Service
apiVersion: v1
metadata:
    name: hello2
spec:
    type: NodePort
    ports:
    - port: 81
      targetPort: 80
      protocol: TCP
      nodePort: 31001
    selector:
      app: hello2